---
version: '3'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - ./:/app
    command: python3 -m pytest -v --capture=no tests/
    depends_on:
      - es01

volumes:
  data01:
    driver: local

networks:
  elastic:
    driver: bridge
